### ISSUE TITLE
Not working with latest kaitai struct ver for windows.

### ISSUE THREAD

**Issue by Shadwar** [kaitai-io/kaitai_struct_visualizer#3]

**Comment by Lerke** [comment]
I've had this issue since coming across Kaitai Struct. Looks sweet, but the visualizer does not work for me.  After using ksv, I get an empty line in cmd and then nothing. kaitai-struct-compiler seems to work fine.

**Comment by GreyCat** [comment]
Native Windows console mode is yet not supported: patches are welcome.

I've heard some success stories with using KS visualizer in Windows with mingw's xterm terminal and some others ANSI-compatible terminal emulators. Alternatively, they say it here that [Windows 10 started to support ANSI sequences in console after some update](http://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/1050078#1050078).

**Comment by Lerke** [comment]
Hi Mikhail,

Can't help but feeling like a bit of an idiot here, but I still cannot seem to get ksv to run in any meaningful way. A while back (version 0.3), I assumed it might've been due to some Windows command line oddities, so I tried using Cygwins xterm, Powershell and even Git bash. These all perform identically to running ksv from the Windows command line. After about half a day of tinkering I unfortunately had to give up on it.

The behaviour I am seeing is as follows. I am using the latest version of both kaitai-struct-visualizer and kaitai-struct-compiler.

    C:\>ksv test.bmp bmp.ksy (I've used the example bmp format from kaitai.io)
        
    C:\>

(This is in Windows cmd, but the behaviour is the same regardless of terminal). I've tried this under both 32 and 64 bit versions of Ruby 2.3.1 and Ruby 2.2.5.

**Comment by GreyCat** [comment]
Um, the problem is that I don't really have interactive access to Windows box to do any decent checks myself.

Probably the right way would be to add some library for Windows that does native console handling. But then again, Windows console is pretty limited (I believe, it is still 16 colors only and can only handle one specific "legacy" encoding that is set up at OS level).

I'll try to look into it somehow, but don't hold you breath for it.

**Comment by Lerke** [comment]
Hi Mikhail,

I've done some debugging and eventually got ksv to run. Albeit not in any way that is useful. I had to change the following to even get it to run on Windows.

* visualizer_main.rb:11 - Change  `system("ksc -- --debug -t ruby '#{fn}' -d '#{code_dir}'")`  to       `system("kaitai-struct-compiler --debug -t ruby #{fn} -d #{code_dir}")`
* tui:12 - change `@cols`, `@rows`, `@seq_clear` and `@seq_sgr0` to hardcoded values. tput is not a cmd command. I'd assume these lines work when using something akin to Cygwin?
* tui:86 - read_char is broken on Windows (Both while using cmd and Cygwin). Assigning a value to `$stdin.echo` will skip the entire method and jump immediately to ensure and then to return input. Commenting out these lines will get ksv to run, but it's not pretty.

I've never written a line of Ruby in my life, so I don't know how to properly work around these issues.  I hope the above is at least helpful to someone. Here's to hoping that ksv will one day work on Windows! (Or at least on my Windows!)

Cheers!

**Comment by GreyCat** [comment]
Thanks for your investigation!

`tput` is a standard way to query terminal control sequences - basically, ANSI or anything else - as long as terminal control sequences database (termcap or terminfo) is present. I guess Windows uses something completely different.

Probably the right way is to use something like Windows console control gem, or better yet, some universal gem that will provide functions for both POSIX and Windows consoles.

**Comment by GreyCat** [comment]
@LogicAndTrick @Lerke I've got my hands on a Windows box and did a couple of tries. A few pitfalls I've learned about:

* Installing Ruby gems on Windows is tricky. Most popular [RubyInstaller](http://rubyinstaller.org/) Windows Ruby distro has somewhat broken `gem` installation that misses any SSL certificate package. One of the solutions is to download it manually and point to it using `SSL_CERT_FILE` environment variable.
* True, there are no `tput`, so if we're going to use ANSI, we'll have to hardcode all the sequences.
* There are two basic Windows console solutions out there:
  * [win32console](https://rubygems.org/gems/win32console/versions/1.3.2) - very old and unmaintained; ships with a binary DLL that would provide access to WinAPI-specific console functions, however, supplied DLL is only good for Ruby 1.8 and 1.9, while there are 2.0, 2.1, 2.2 and 2.3 (latest stable) already.
  * [https://github.com/adoxa/ansicon](ANSICON) - a small windows utility that hooks upon terminal output functions and tries to handle ANSI sequences; however, it works only for output, not providing any keypress getting functions.
* There seem to be no way for current Ruby to get keypresses in Windows console. The one possible way out would be resurrecting `win32console` module and porting / rebuilding it for modern Ruby & Windows implementations. I'm not a Win32 programmer, so probably it's better for someone else to take a look.

**Comment by LogicAndTrick** [comment]
The native Ubuntu tools in Windows 10 could be an option as well, but `ksc` and most Java stuff locks up in the W10 Bash terminal for now, pending the next service pack for a fix. That's no good for Windows <= 8 users and might even still have the same console-related issues once the Java patch comes through anyway.

I've not done any console stuff with Java, but would it be much difficulty to write the visualiser as a Java console app instead? A few months ago I wrote a dynamic Java runtime that can compile/parse streams for a proof of concept GUI visualiser/IDE type thing, I'm sure it could work for a console app as well.

[Here's a basic example](https://gfycat.com/EasyMemorableAfricanhornbill) of what I mean:
![screenshot](https://zippy.gfycat.com/EasyMemorableAfricanhornbill.gif)

The dependency of Ruby is a bit of a pain on Windows, because as you have discovered, the Ruby experience on Windows isn't really great. Since Java is required anyway for the compiler, using it for the visualiser as well seems okay. Alternatively I find that Python works with Windows pretty well, it might be a good option too.

**Comment by GreyCat** [comment]
That were exactly my thoughts: I'm trying to get a Swing-based Java visualizer running now. Here's what I've got so far:

![visualizer-java-v0](https://cloud.githubusercontent.com/assets/157154/19599556/f533cdb2-97a9-11e6-8185-e07676f50aac.png)

Nothing fancy, still a lot to do.

That IDE of yours looks really cool too! Why haven't you told me about it eariler? May be you'll publish it, so we can look more into it?

**Comment by Lerke** [comment]
Wow, no kidding huh?

I started work on a similar (!) project in JavaFX about a month ago. I got up to importing the .java source files `ksc` creates and started working on a hex-viewer element before having to postpone my progress due to lack of time. I meant to go back to it at some point, but my progress is certainly lacking when compared to yours @GrayCat, and certainly yours @LogicAndTrick!

![nokidding](https://cloud.githubusercontent.com/assets/3271167/19610229/95fb0a72-97db-11e6-81b4-49f6172dca20.PNG)

@LogicAndTrick Your app looks really neat! Would agree with @GreyCat, consider publishing it!

**Comment by GreyCat** [comment]
Hey, people, you're all crazy ;) Ok, so let's get public and get collaborating on it, what the heck. We've already wasted *so* much time digging in that stuff alone :)

So, here's my take at it: https://github.com/kaitai-io/kaitai_struct_gui

No READMEs, no decent project yet (only the IDEA project), etc.

**Comment by LogicAndTrick** [comment]
Haha, looks like we all had the same idea :)
My stuff's fairly primitive and needs a lot more work but I'm happy to publish what I've done so far. Give me a day or two to clean up some cruft in the project and I'll push it up.

**Comment by LogicAndTrick** [comment]
Okay, here's mine: https://github.com/LogicAndTrick/kaitai_struct_ide

I didn't know that Java files could be dynamically compiled and loaded or I might not have written a dynamic runtime! Having the runtime does let me add a lot of extra metadata though, and that lets me do neat stuff like printing the results inline with the hex dump (which I like, but I don't know if everyone would agree).

**Comment by GreyCat** [comment]
@LogicAndTrick Finally managed to take a closer look at your project. It is indeed impressive - it's a whole another implementation of language parser + interpreter. It's probably something worth separation into distinct library — but, obviously, it's a huge project and, at the very least, it's a good idea to start with ensuring that it passes our test suite. For that, you'll have to port all the specs.

**Comment by GreyCat** [comment]
@Shadwar @Lerke @LogicAndTrick Finally, I've got this ksv (i.e. Ruby + console one) to run on Windows:

![visualizer-console-windows](https://cloud.githubusercontent.com/assets/157154/19858894/46a97f7e-9f94-11e6-80db-de85a6bf2bb1.png)

Some comments on how it's done:

* I've separated 2 console implementations (ANSI and Windows) into ConsoleANSI and ConsoleWindows classes. Windows console is implemented as dynamically linked calls using `Win32API` module, hooking right into `kernel32` calls. `Win32API` seems to be standard Ruby module on any Windows Ruby build, so it should be pretty nice and portable.
* Windows console lacks modern zillions of colors, there are only 16 of them, there are no good variety of shades of gray (that I've used to highlight sub-sub-sub-structures). Thus I've kind of picked up something more or less random just for the sake of demonstration.
* It seems to be pretty slow (dunno if it's because of Ruby or because of Win32API calls), so crude "we'll redraw everything on every keypress" causes lots of flicker. Need to improve that stuff.

**Comment by tschoening** [comment]
> Um, the problem is that I don't really have interactive access to Windows box to do any decent checks myself.

@GreyCat I have a German Win 7 Ultimate x64 System Builder lying around here for years unopened. If you are interested and willing to provide me your address, I'll happily send it to you.

**Comment by GreyCat** [comment]
@tschoening Thanks for the offer, but the point here wasn't about licenses (I guess I have plenty of them lying around), or even about having some spare physical hardware to run it at, but mostly about time needed to do that install, set up all the stuff, etc., and my general Windows skills (as it was like ~15 years ago when I was programming something on Windows, so I could say that my WinAPI knowledge is, well, very dated). Right now I've got a couple of Windows VMs set up to try things out at, and finally applied some fixes to get ksv to run on Windows.

I guess this issue should be closed, as ksv actually *runs on Windows* now, all the other matters (like usability, that `q` to quit stuff, etc, etc) should be probably discussed separately.
