### ISSUE TITLE
Win32API is not in the ruby standard library since version 1.9.2

### ISSUE THREAD

**Issue by humdogm** [kaitai-io/kaitai_struct_visualizer#48]
According to [the developer of win32-api](https://www.rubydoc.info/gems/win32-api/1.10.1), `The current Win32API library that ships with the standard library has been slated for removal from Ruby 2.0`. I installed the latest version of ruby (3.0) to run ksv. Running ksv I get this error: `<internal:C:/Program Files/Ruby/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in 'require': cannot load such file -- Win32API (LoadError)` . It is a requires of console_windows.rb . The gem [win32-api](https://www.rubydoc.info/gems/win32-api/1.10.1) is apparently a replacement for it, last updated April 2021.

**Comment by generalmimon** [comment]
Resolved by https://github.com/kaitai-io/kaitai_struct_visualizer/pull/49 - we don't use `Win32API` anymore.

**Comment by generalmimon** [comment]
@demberto:

> I had the same problem. I installed the `win32api` gem and the problem was solved

Well, the problem really was solved in https://github.com/kaitai-io/kaitai_struct_visualizer/pull/49, I just have to release a new version of `kaitai-struct-visualizer` to RubyGems.

And BTW, both "win32api" gems I know of (https://github.com/ruby/win32api and https://github.com/cosmo0920/win32-api) are deprecated, so it's better not to use them. That's why I suggested to use Fiddle in https://github.com/kaitai-io/kaitai_struct_visualizer/pull/49#issuecomment-1213525769 instead, and AFAICT it works well.

**Comment by generalmimon** [comment]
@demberto I encourage you to try out the [`master` branch](https://github.com/kaitai-io/kaitai_struct_visualizer/tree/master) and see if you find any issues there.

Running `ksv` from source code without installing it with RubyGems first is easy - just instead of running `ksv` (installed as a global command), you run [`bin/ksv`](https://github.com/kaitai-io/kaitai_struct_visualizer/blob/78f7ac22210d3a59c1593a785d58bd2d86f8e1fc/bin/ksv) in the cloned 
https://github.com/kaitai-io/kaitai_struct_visualizer repository. It's ready to be run like this (even when it's not installed in the usual directory where RubyGems installs packages and scripts).
